apiVersion: v1
kind: Service
metadata:
  name: conformance-static-allocation-check
  namespace: gateway-backend
spec:
  type: LoadBalancer
  loadBalancerIP: 198.18.1.254
  selector:
    app: benchmark-backend
  ports:
  - port: 18081
    targetPort: 8081
